FROM debian:bookworm

RUN apt-get update -y \
 && apt-get install -y php8.2-fpm php8.2-mysql curl default-mysql-client unzip \
 && rm -rf /var/lib/apt/lists/*

# Télécharger WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

# Modifie PHP-FPM pour qu’il écoute sur le port 9000
RUN sed -i 's|^listen = .*|listen = 9000|' /etc/php/8.2/fpm/pool.d/www.conf

# Créer le dossier WordPress et donner les droits
RUN mkdir -p /var/www/html \
    && chown -R www-data:www-data /var/www/html

COPY ./tools/script.sh /usr/local/bin/script.sh

RUN chmod +x /usr/local/bin/script.sh

WORKDIR /var/www/html

ENTRYPOINT ["/usr/local/bin/script.sh"]
