FROM debian:bookworm

RUN apt update; \
    apt install -y nginx openssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/tgoudman.key \
    -out /etc/ssl/certs/tgoudman.crt \
    -subj "/C=FR/ST=Normandie/L=LeHavre/O=42 Le Havre/OU=tgoudman/CN=tgoudman.42.fr"

COPY ./tools/certs.sh /tmp/certs.sh

RUN chmod +x /tmp/certs.sh

COPY ./conf/default /etc/nginx/sites-available/default


ENTRYPOINT ["/tmp/certs.sh"]